on:
  workflow_dispatch:

name: Start Self-Hosted Runner

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 
        
    - name: Run Azure PowerShell inline script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          Get-AzSubscription ${{secrets.AZURE_CREDENTIALS.subscriptionId}} | Set-AzCOntext
          Start-AzVM -ResourceGroupName ${{vars.RUNNER_RESOURCE_GROUP}} -Name ${{vars.RUNNER_VM_NAME}} 
        azPSVersion: "latest"
